# fly.toml app configuration file generated for bitter-wood-7750 on 2024-01-15T11:50:32+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bitter-wood-7750"
primary_region = "hkg"

[build]

[env]
  PORT = "3001" # add this

[http_service]
  internal_port = 3001 # ensure that this is same as PORT
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
